Quizly-Project/quizly-frontend

- src/components/3d/Environment/OLevel.jsx
- src/components/3d/Environment/XLevel.jsx
- src/components/3d/Mesh/ModelComponent.jsx
- src/components/3d/Mesh/OtherModelComponent.jsx
- src/pages/Game.jsx
**작업 내용**
- 원숭이 모델에 물리엔진을 적용하였습니다.
- 원숭이가 바라보는 방향으로 고개를 돌리도록 수정하였습니다.
**관련 이슈**
- #14 특정 각도에 따라 모델이 보이지 않는 문제
> 모델에 물리엔진 적용

- src/components/3d/Mesh/CharacterController.jsx
- src/pages/Game.jsx
**작업 내용**
1. 서버->클라이언트 리스너
- connect: 연결 성공
- everyonePosition: 기존 접속 중인 클라이언트의 위치 정보
- newClientPosition: 다른 클라이언트가 새로 접속
- theyMove: 다른 클라이언트가 이동
- someoneExit: 다른 클라이언트가 연결 해제
- disconnect: 연결 해제
2. 클라이언트->서버 이벤트
- iMove: 클라이언트 이동 시 좌표 정보 전달
> Event listener 이름 수정

- src/components/common/CountTimer/CountTimer.jsx
- src/pages/Game.jsx
구현
---
- 퀴즈 데이터를 받아오는 quiz소캣 리스너를 구현했습니다.
- 퀴즈 타이머를 시작 timerStart 소캣 리스너를 구현했습니다.
- 퀴즈 타이머를 종료하는 timeout 소캣 리스너를 구현했습니다.
bug fix
---
- 퀴즈에 접속하는 유저가 이미 들어와있는 유저를 렌더링하지 못하는 문제가 있었습니다 .
- handleEveryonePosition 함수에서 배열로 받아오던 좌표 데이터를 객체로 변환했습니다.
> 퀴즈게임 퀴즈시작기능

- src/components/common/Text/Text.jsx
- src/pages/Game.jsx
- src/pages/Game/Question.jsx
- src/pages/Game/QuizStartButton.jsx
- src/styles/game.css
**작업 내용**
- 퀴즈 시작 버튼을 누를 때마다 다음 퀴즈 질문이 보이도록 하는 기능을 추가하였습니다.
> 퀴즈 시작 버튼 누르면 질문 시각화

- src/pages/Game.jsx
- src/store/socketStore.js
- src/utils/socketHandlers.js
- socket 상태를 전역상태로 분리해 socketStore를 구현했습니다.
- socketHandler를 분리해 createSocketHandlers함수를 구현했습니다.
> 소캣 상태 전역상태로 분리 및 소캣 핸들러 분리

- src/api/axios.js
- src/components/common/RoomCodeModal/RoomCodeModal.jsx
- src/components/common/RoomCodeModal/RoomCodeModal.module.css
- src/pages/Dashboard/Dashboard.jsx
- src/pages/Game.jsx
- src/pages/SignIn.jsx
- src/pages/SignUp.jsx
- src/store/socketStore.js
- Dashboard 컴포넌트에 useSocketStore를 사용해 socket상태를 전역으로 관리합니다.
- RoomCodeModal 컴포넌트를 구현했습니다.
- RoomCodeModal컴포넌트에서 방으로 이동 버튼 클릭시 해당 퀴즈 방으로 이동합니다.
> 선생님 퀴즈방 생성시 방코드 생성 후 방으로 이동

- src/pages/Dashboard/Dashboard.jsx
- src/pages/Game.jsx
- src/store/socketStore.js
- 선생님이 방을 생성시 세션스토리지에 isTeacher:true를 저장했습니다.
- 퀴즈방에 참가시 닉네임 상태를 세션스토리지에 저장했습니다.
> 새로고침시 유저 상태 유지

- src/pages/Dashboard/Dashboard.jsx
- src/pages/Game.jsx
- 선생님이 방 생성을 눌렀을시 버튼이 disable됩니다.
- 학생의 소캣 이벤트리스너가 등록되지 않던 문제를 useEffect 의존성 배열에 [socket, isConnected]를 추가했습니다.
> 선생님이 퀴즈를 출제했을때 학생에게 전될되지않는 문제 해결

- src/App.jsx
- src/components/Game/CommonUI.jsx
- src/components/Game/GameUserInterface.jsx
- src/components/Game/Question.jsx
- src/components/Game/QuizResultText.jsx
- src/components/Game/QuizStartButton.jsx
- src/components/Game/StudentUI.jsx
- src/components/Game/TeacherUI.jsx
- src/pages/Game.jsx
- src/utils/socketHandlers.js
- Game 페이지 컴포넌트에 학생과 선생님, 공통 UI를 분리했습니다.
- 학생 컴포넌트인 StuentUI를 만들었습니다.
- 아직까지는 구현된 하위 컴포넌트가없습니다.
- 선생님 컴포넌트인 TeacherUI를 만들었습니다.
-  퀴즈를 시작하는 버튼인 QuizStartButton 하위 컴포넌트가 있습니다.
- 공통 컴포넌트인 CommonUI를 만들었습니다.
- 퀴즈 문제 Question 하위 컴포넌트가 있습니다.
- 퀴즈의 결과를 알려주는 QuizResultText 하위 컴포넌트가 있습니다.
> Game 컴포넌트 선생님, 학생 인터페이스 분리

- src/components/3d/Environment/Beachside.jsx
**작업 내용**
- Beachside component를 export default로 수정하였습니다.
> Beachside export 설정 수정

- src/components/Game/CommonUI.jsx
- src/components/Game/GameUserInterface.jsx
- src/components/Game/TeacherUI.jsx
- src/pages/Game.jsx
- src/utils/socketHandlers.js
- handleEveryonePosition함수에서 인자를 하나의 변수에서 객체로 변경했습니다.
> handler함수 인자 객체로 변경

- src/App.jsx
- src/components/3d/Environment/Lights.jsx
- src/components/3d/Environment/OLevel.jsx
- src/components/3d/Environment/XLevel.jsx
- src/components/3d/Mesh/Character.jsx
> 모델에 그림자 추가

- src/components/3d/Mesh/Character.jsx
- src/components/3d/Mesh/CharacterController.jsx
- src/components/3d/Mesh/OtherCharacterController.jsx
**작업 내용**
- 모델에 애니메이션을 추가하였습니다.
1. CharacterController
- 사용자 움직임에 따라 애니메이션을 수행합니다.
- 가만히 있을 때: Idle_A
- 걸을 때: Walk
- 점프: Jump
2. OtherCharaterController
- 다른 클라이언트가 움직임에 따라 애니메이션(Idle_A)를 수행합니다.
- 다른 클라이언트도 움직임에 따라 다른 애니메이션을 수행하도록 하기 위해선 서버로부터 WorldPosition과 더불어 어떤 actionType을 수행 중인지에 대한 정보도 받아와야 합니다.
**관련 이슈**
- "#31 캐릭터 애니메이션 추가 필요"를 해결하였습니다.
- "#37 다른 클라이언트의 움직임에 따라 서로 다른 actionType 렌더링" 이슈가 추가되었습니다.
> 모델 애니메이션 추가

- README.md
- src/App.jsx
- src/components/Game/GameContainer/GameContainer.jsx
- src/components/Game/GameContainer/GameContainer.module.css
- src/components/Game/GameUserInterface/GameUserInterface.jsx
- src/components/Game/GameUserInterface/GameUserInterface.module.css
- src/components/Game/NickNameInput/NickNameInput.jsx
- src/components/Game/NickNameInput/NickNameInput.module.css
- src/pages/Game.jsx
- src/utils/socketHandlers.js
> 게임컴포넌트 3D컴포넌트 UI컴포넌트 분리

- src/pages/Game.jsx
**작업 내용**
- 데모 발표를 위해 Physics의 debug off하였습니다.
> 디버그 모드 off

- src/components/3d/Mesh/CharacterController.jsx
- src/components/Game/CommonUI.jsx
- src/components/Game/GameContainer/GameContainer.jsx
- src/components/Game/GameUserInterface/GameUserInterface.jsx
- src/components/Game/ParticipantList/ParticipantList.jsx
- src/components/Game/ParticipantList/ParticipantList.module.css
- src/components/Game/TeacherUI/TeacherUI.jsx
- src/pages/Game.jsx
- src/utils/socketHandlers.js
- ParticipantList 컴포넌트를 구현했습니다.
- CharacterController에 있던 CameraControls를 상위 컴포넌트인 Game컴포넌트에 배치했습니다.
> feat: 선생님시점 학생 시점으로 전환

- src/components/3d/Environment/Island.jsx
- src/components/3d/Environment/Lights.jsx
- src/components/3d/Environment/SpotLights.jsx
- src/pages/Game.jsx
**작업 내용**
- OX 구역에 spotlight를 추가하였습니다.
**추가로 필요한 작업**
- 정답이 나왔을 때, 해당 구역에만 잠시동안 spotlight를 비추도록 해야 합니다.
> 간단한 Spotlight 구현

- src/components/3d/Mesh/OtherCharacterController.jsx
- src/components/Game/GameContainer/GameContainer.jsx
- src/pages/Game.jsx
- src/store/socketStore.js
- src/utils/socketHandlers.js
**작업 내용**
- 이제 클라이언트별로 다른 모델이 적용됩니다.
- 최대 8명까지 접속 가능합니다.
**관련 이슈**
- "#11 특정 클라이언트에게 모델이 보이지 않는 문제"를 해결하였습니다.
> 클라이언트별 다른 모델 지정

- src/components/3d/Environment/Blackboard.jsx
- src/components/3d/Mesh/Character.jsx
- src/pages/Game.jsx
**작업 내용**
- 기존의 하드코딩 되어있던 질문을 현재 풀고 있는 질문이 출력되도록 수정하였습니다.
**버그**
- 중간에 학생이 추가적으로 들어올 경우 칠판이 보이지 않습니다.
- 질문의 길이에 따라 텍스트 정렬이 맞지 않습니다.
> 칠판에 현재 질문 받아서 출력

- src/pages/Game.jsx
- Game컴포넌트에서 [isTeacher, selectedStudent, setTeacherView]의존성 배열을 가지는 useEffect의 조건문에서 selectedStudent조건을 제거했습니다
> fix: 선생님이 학생 시점에서 선생님 시점으로 돌아왔을때 학생을 기준으로 고정되는 문제 해결

- src/components/Game/GameContainer/GameContainer.jsx
- src/pages/Game.jsx
- src/utils/socketHandlers.js
**작업 내용**
- 정답이 1(O)이면 O 영역에 스포트라이트
- 정답이 2(X)이면 X 영역에 스포트라이트
- 를 비추도록 하였습니다.
> 정답에 따라 스포트라이트 비추기

- src/components/Game/GameContainer/GameContainer.jsx
- src/components/common/ChatComponent/ChatComponent.jsx
- src/pages/Dashboard/Dashboard.jsx
- src/pages/Landing.jsx
- src/store/socketStore.js
- GameContainer에 있던 socketInit을 landing 페이지 컴포넌트로 이동했습니다.
- GameContainer에 error 소캣 이벤트 리스너를 추가해 에러가 발생하면 소캣을 닫고 루트 페이지로 이동합니다.
- landing페이지 컴포넌트에서  roomCheck 소캣을 추가해 유효성 검사를 실행합니다.
> feat: 퀴즈방 유효성 검사

- src/components/Game/GameContainer/GameContainer.jsx
- src/components/Game/StudentResult/StudentResult.jsx
- src/components/Game/StudentResult/StudentResult.module.css
- src/components/Game/TeacherUI/TeacherUI.jsx
- src/components/Game/TeacherUI/TeacherUI.module.css
- src/components/common/ChatComponent/ChatComponent.jsx
- src/utils/socketHandlers.js
> feat: 선생님 대시보드

- src/pages/Dashboard/Dashboard.jsx
- Dashborad 컴포넌트에서 [isConnected, socket]의존성 배열을 가지는 useEffect에서 quizId가 null인 경우 바로 리턴하도록 수정했습니다.
> fix: 선생님이 방을 나갔을때 error소캣 이벤트 발생 오류 해결

- src/pages/Dashboard/Dashboard.jsx
- Dashboard 컴포넌트가 처음 마운트될때 isConnected가 true이면 소캣disconnect
> feat: 대시보드 컴포넌트가 마운트될때 connect 되어있다면 disconnect

- src/components/3d/Mesh/Character.jsx
- src/components/3d/Mesh/CharacterController.jsx
- src/components/3d/Mesh/OtherCharacterController.jsx
- src/pages/Game.jsx
- src/utils/socketHandlers.js
- socketHandler에서 handleTimeOut 메서드에서 인원수가 2명 이한경우 예외처리를 제거했습니다
- Character 컴포넌트에서 getRankMedal 함수를 추가해 순위별로 이름에 효과를 부여했습니다
> feat: 순위에 따른 캐릭터 닉네임에 효과 추가

- src/components/3d/Mesh/OtherCharacterController.jsx
- OtherCharacterController 컴포넌트에 useMemo의존성 배열에 rank를 추가했습니다.
> fix: 나를 제외한 캐릭터에 메달이 안보이는 문제 해결

- src/components/3d/Environment/Blackboard.jsx
- src/components/3d/Mesh/Character.jsx
- src/components/3d/Mesh/CharacterController.jsx
- src/pages/Game.jsx
- src/pages/SignUp.jsx
- src/styles/game.css
**작업 내용**
- 캐릭터의 크기를 증가시켰습니다.
- 문제를 빠르게 출력합니다.
> 캐릭터 크기 증가, 문제 빠르게 출력

- src/components/3d/Mesh/Character.jsx
- src/components/3d/Mesh/CharacterController.jsx
- src/components/Game/GameContainer/GameContainer.jsx
- src/pages/Game.jsx
- src/utils/socketHandlers.js
**작업 내용**
- 정답을 맞히면 춤을 춥니다. (나한테만 보임)
- action: Fly 사용
**추가적으로 필요한 작업**
- 선생님 시점에서도 학생이 춤추는 것을 보이게 해야 합니다.
> 정답 맞히면 춤추기 기능 추가

- src/components/3d/Mesh/CharacterController.jsx
- src/components/3d/Mesh/OtherCharacterController.jsx
- src/components/Game/GameContainer/GameContainer.jsx
- src/components/Game/TopThreeParticipants/TopThreeParticipants.jsx
- src/pages/Game.jsx
- src/utils/socketHandlers.js
**작업 내용**
- 다른 클라이언트가 정답을 맞힐 시 춤을 춥니다.
- 선생님 시점에서도 정답자가 춤을 춥니다.
> 다른 클라이언트가 맞히면 춤추도록

- src/components/Game/GameContainer/GameContainer.jsx
> feat: 배경 효과음 추가

- src/components/3d/Mesh/CharacterController.jsx
- isChatFocused를 isInputChatFocused로 수정했습니다.
> fix: isChatFocused 오타 수정

- src/components/3d/Mesh/CharacterController.jsx
- src/components/Game/GameContainer/GameContainer.jsx
- src/store/inputFocusedStore.js
- src/utils/socketHandlers.js
**작업 내용**
- 오타를 수정했습니다.
- 나의 초상화가 안 보이는 문제를 해결하였습니다.
> 나의 초상화 안 보이는 문제 해결

- src/components/Game/CommonUI.jsx
- src/components/Game/GameContainer/GameContainer.jsx
- src/store/quizRoomStore.js
- CommonUI 컴포넌트 TopThreeParticipants 컴포넌트 조건에 quizResult를 추가했습니다.
> feat: 상위3명 뷰 오류

- src/components/Game/CommonUI.jsx
- src/components/Game/FinalTopThreeParticipants/FinalTopThreeParticipants.jsx
- src/components/Game/GameContainer/GameContainer.jsx
- src/components/Game/GameContainer/GameContainer.module.css
- src/components/Game/LiveKit/VideoAudio.tsx
- src/components/Game/MyCameraOtherVoice/MyCameraOtherVoice.tsx
- src/components/Game/QuizProgress/QuizProgress.module.css
- src/components/Game/RemoteVideoDisplay/RemoteVideoDisplay.tsx
- src/components/Game/VoiceChat/VoiceChat.tsx
- src/store/liveKitStore.ts
- src/store/quizRoomStore.js
- audioTrack과 videoTrack을 분리하여 관리합니다.
> feat: 퀴즈 입장시 화상카메라와 음성채팅 및 상위3명 화상카메라

- src/components/Game/LiveKit/LiveKit.tsx
- tsconfig.json
> feat: LiveKit env설정

- src/components/Game/GameContainer/GameContainer.jsx
- src/components/Game/GameContainer/GameContainer.module.css
- src/components/Game/MyCameraOtherVoice/MyCameraOtherVoice.tsx
- MyCameraOtherVoice컴포넌트에 props로 selectedStudent을 전달합니다.
> feat: 학생 클릭시 화상카메라 선생님으로 전환

- src/components/common/MultipleChoiceForm/MultipleChoiceForm.jsx
- src/components/common/ShortAnswerForm/ShortAnswerForm.jsx
- ShortAnswerForm컴포넌트를 퀴즈 생성에 맞는 폼형식으로 수정했습니다.
> feat: 도전골든벨 퀴즈문제 생성

- src/components/3d/Environment/BasicSpotLights.jsx
- src/components/3d/Environment/ExplosionConfetti.jsx
- src/components/3d/Environment/SpotLights.jsx
- src/pages/Game.jsx
**작업 내용**
- 골든벨 모드에서 정답자 머리 위로 스포트라이트 추가하였습니다.
- 정답자 나오면 컨페티가 나옵니다.
> 골든벨 스포트라이트, 컨페티 추가

- src/components/3d/Environment/BrokenLand.jsx
- BrokenLand 컴포넌트에 RigidBody를 제거했습니다.
> fix: 섬 땅꺼짐 시 rigidbody가 제거되지 않는 문제 해결

- src/components/3d/Environment/Arrow3D.jsx
- src/components/3d/Mesh/Character.jsx
- src/components/3d/Mesh/OtherCharacterController.jsx
- src/pages/Game.jsx
- src/styles/game.css
- Arrow3D 컴포넌트를 추가했습니다.
- Game컴포넌트에서 selectedStudent와 nickname이 동일하면 Arrow3D컴포넌트를 렌더링합니다.
> feat: 선생님이 학생 선택시 화살표 추가

- src/components/common/Button/Button.module.css
- src/components/common/InputField/InputField.module.css
- src/components/common/MyQuiz/MyQuiz.jsx
- src/components/common/MyQuiz/MyQuiz.module.css
- src/components/common/QuizCard/QuizCard.jsx
- src/components/common/QuizCard/QuizCard.module.css
- src/components/common/QuizDetailModal/QuizDetailModal.jsx
- src/components/common/QuizDetailModal/QuizDetailModal.module.css
- src/components/common/QuizList/QuizList.module.css
- src/components/common/SearchBar/SearchBar.jsx
- src/components/common/SelectCreateQuiz/SelectCreateQuiz.jsx
- src/components/common/SelectCreateQuiz/SelectCreateQuiz.module.css
- src/components/common/Sidebar/Sidebar.jsx
- src/components/common/Sidebar/Sidebar.module.css
- src/pages/Dashboard/Dashboard.jsx
**작업 내용**
- 둘러보기, 퀴즈 만들기, 내 퀴즈, sidebar, quiz Card, css 수정
> 교사 페이지 css 전면 수정

- src/App.jsx
- src/pages/Landing/Landing.jsx
- src/pages/Landing/Landing.module.css
- src/pages/MainPage/MainPage.module.css
- src/styles/App.css
**작업 내용**
- landing page css 수정
> landing page css 수정

- src/components/common/SelectCreateQuiz/SelectCreateQuiz.jsx
> 퀴즈 type 이름 변경

- src/components/common/QuizCard/QuizCard.module.css
- src/components/common/Sidebar/Sidebar.module.css
**작업 내용**
- sidebar 길이가 페이지 별로 일정하지 않던 문제 해결
- 반응형으로 브라우저 크기가 작아지면 사이드바도 작아짐
> sidebar CSS 수정

- src/pages/Game.jsx
- src/pages/QuizResult.jsx
> Fix result page

- src/pages/QuizResult.jsx
- src/styles/QuizResult.css
> Quiz result css

- src/components/Game/NickNameInput/NickNameInput.jsx
- src/components/Game/NickNameInput/NickNameInput.module.css
**작업 내용**
- nickname input css 수정
- nickname 입력 후 엔터를 쳐서 입장 가능하도록 수정
> nickname input css 수정

- src/styles/QuizResult.css
> feat: 스크롤 기능 추가 및 버튼 크기 수정

- src/components/3d/Mesh/Character.jsx
- src/styles/game.css
**작업 내용**
- 화이트보드 css 적용
- 캐릭터별 화이트보드 색상 추가
> 골든벨 화이트보드 수정

- src/components/3d/Mesh/Character.jsx
> feat: 화이트보드에 뱃지를 추가한다.

- src/components/Game/FinalTopThreeParticipants/FinalTopThreeParticipants.jsx
- src/components/Game/RemoteVideoDisplay/RemoteVideoDisplay.tsx
**작업 내용**
- top three 리더보드에서 내 화상 화면만 보이지 않던 문제 해결
> top three leaderboard에서 내 카메라도 보이게 수정
